name: Build JUCE Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # Si tu veux cloner JUCE directement (optionnel)
      # - name: Clone JUCE
      #   run: |
      #     git clone https://github.com/juce-framework/JUCE.git juce

      - name: Install JUCE dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev libx11-dev libxinerama-dev libxrandr-dev \
            libxcursor-dev libxcomposite-dev libxrender-dev \
            libfreetype6-dev libglu1-mesa-dev

      - name: Extract plugin sources
        run: |
          rm -rf plugins
          if ls *.zip 1> /dev/null 2>&1; then
            echo "ZIP trouvé, extraction..."
            unzip *.zip -d plugins
          else
            echo "❌ Aucun fichier ZIP trouvé. Rien à extraire."
            exit 1
          fi

      - name: Configure CMake
        run: |
          cd plugins
          cmake .

      - name: Build plugin
        run: |
          cd plugins
          cmake --build build --config Release -- -j2

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v5
        with:
          name: juce-plugin
          path: plugins/build
