name: Build JUCE Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone JUCE
        run: |
          git clone --depth 1 https://github.com/juce-framework/JUCE.git /root/juce

      - name: Install JUCE dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev libx11-dev libxinerama-dev libxrandr-dev \
            libxcursor-dev libxcomposite-dev libxrender-dev \
            libfreetype6-dev libglu1-mesa-dev

      - name: Prepare plugin build folder
        run: |
          rm -rf build
          mkdir build

      - name: Configure CMake
        run: |
          cmake -B build -S . -DJUCE_PATH=/root/juce

      - name: Build plugin
        run: |
          cmake --build build --config Release -- -j2

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v5
        with:
          name: juce-plugin
          path: build
